image: node:10.10.0

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r docs/.vuepress/public/* .public
    - mv .public public
    - npm run docs:build
  artifacts:
    paths:
      - public
  only:
    - master
